### ISSUE TITLE
Please update blob files

### ISSUE THREAD

**Issue by vikoadi** [Anik1199/proprietary_vendor_xiaomi#1]
Please update blob files
at least it lacks

- libfmjni.so
- camera.msm8916.so

**Comment by Anik1199** [comment]
Why should i? Your camera and FM not working? Do you ever wondered about how they works?

**Comment by vikoadi** [comment]
well, I try to build CM13 and it failed with no target for camera.msm8916.so.
Shouldn't it included here?
